### INFO log
GET {{BASE_URL}}/logs/INFO?message=hello-info

### DEBUG log
GET {{BASE_URL}}/logs/DEBUG?message=test-debug

### ERROR log
GET {{BASE_URL}}/logs/ERROR?message=oops


### Exception log
GET {{BASE_URL}}/logs/exception?message=boom


### Bulk 50 INFO logs with 50ms delay
GET {{BASE_URL}}/logs/bulk?count=50&level=INFO&sleepMs=50


### Random log (any level)
GET {{BASE_URL}}/logs/random
